USE Formula_1;

SELECT * FROM CONSTRUCTORS;

INSERT IGNORE INTO CONSTRUCTORS VALUES (11,'AUDI',0,0);
SELECT * FROM CONSTRUCTORS WHERE CNo = 11;

UPDATE CONSTRUCTORS SET CPodiums = 10, CWins = 5 WHERE CNo = 11;
SELECT * FROM CONSTRUCTORS WHERE CNo = 11;


DELETE FROM CONSTRUCTORS WHERE CNo = 11;
SELECT * FROM CONSTRUCTORS WHERE CNo = 11;


SYSTEM EXIT