CREATE DATABASE Sales_Management;

USE Sales_Management;

CREATE TABLE Salesmen(
Sid VARCHAR(5) NOT NULL PRIMARY KEY,
Sname VARCHAR(20) NOT NULL,
City VARCHAR(15) NOT NULL,
Salary NUMERIC(8,2) CHECK (Salary > 0),
Tgttoget NUMERIC(10,2) CHECK (Tgttoget > 0),
Comm NUMERIC(5,2) CHECK (Comm > 0));

CREATE TABLE Customers(
Cid VARCHAR(5),
Cname VARCHAR(20) NOT NULL,
City VARCHAR(15) NOT NULL,
State VARCHAR(15),
Pincode NUMERIC(6),
Class VARCHAR(1) DEFAULT 'A' NOT NULL CHECK (Class IN ('A','B','C')));

CREATE TABLE Orders(
Oid VARCHAR(5) NOT NULL PRIMARY KEY,
Cid VARCHAR(5),
Sid VARCHAR(5),
Product VARCHAR(20),
Qty NUMERIC(5),
Odate DATE NOT NULL,
O_amt NUMERIC(8,2) CHECK (O_amt >= 0.00),
FOREIGN KEY (Sid) REFERENCES Salesmen(Sid) ON DELETE CASCADE);