-- DATA MANIPULATION LANGUAGE (DML)

USE Formula_1;

-- SELECT, INSERT, UPDATE DELETE.

-- SELECT

SELECT * FROM CONSTRUCTORS;
SELECT * FROM DRIVERS;
SELECT * FROM RACES;
SELECT * FROM TIMINGS;

-- INSERT

INSERT INTO CONSTRUCTORS VALUES(11, 'PORSCHE', 5, 0);
SELECT * FROM CONSTRUCTORS WHERE CNo = 11;

INSERT INTO RACES (GPName) VALUE ('GERMANY');
SELECT * FROM RACES WHERE GPName = 'GERMANY';

INSERT INTO TIMINGS (GPName) VALUE ('GERMANY');
SELECT * FROM TIMINGS WHERE GPName = 'GERMANY';

INSERT INTO DRIVERS VALUES (59,'A.KRISH',6,0,11,'GERMANY'),(88,'L.SILVER',4,0,11,'GERMANY');
SELECT * FROM DRIVERS WHERE CNo = 11;

-- UPDATE

UPDATE CONSTRUCTORS SET CWins = 2 WHERE CNo = 11;
SELECT * FROM CONSTRUCTORS WHERE CNo = 11;

UPDATE DRIVERS SET DWins = 1 WHERE DNo IN (59,88);
SELECT * FROM DRIVERS WHERE CNo = 11;

UPDATE RACES SET FIRST_PLACE = 59, SECOND_PLACE = 88, THIRD_PLACE = 6 WHERE GPName = 'GERMANY';
SELECT * FROM RACES WHERE GPName = 'GERMANY';

UPDATE TIMINGS SET DNo = 59, FASTEST_LAP = '01:02:46', CNo = 11, FASTEST_PIT_STOP = '00:04:21' WHERE GPName = 'GERMANY';
SELECT * FROM TIMINGS WHERE GPName = 'GERMANY';

-- DELETE

DELETE FROM RACES WHERE GPName = 'GERMANY';
DELETE FROM CONSTRUCTORS WHERE CNo = 11;

SELECT * FROM CONSTRUCTORS WHERE CNo = 11;
SELECT * FROM RACES WHERE GPName = 'GERMANY';
SELECT * FROM TIMINGS WHERE GPName = 'GERMANY';
SELECT * FROM DRIVERS WHERE CNo = 11;